# Generated by Django 4.0.4 on 2022-06-01 12:56

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_answer_reputation_question_reputation'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('manager', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/user_01.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
