# Generated by Django 4.0.4 on 2022-04-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.CharField(blank=True, choices=[('r', 'Correct'), ('w', 'Wrong')], max_length=1, null=True),
        ),
    ]
