# Generated by Django 4.0.4 on 2022-04-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Like'), (-1, 'Dislike')], null=True),
        ),
    ]
