# Generated by Django 4.0.4 on 2022-04-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_like_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeButton',
        ),
    ]
