# Generated by Django 4.0.4 on 2022-04-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_likebutton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Like'), (0, 'Unlike'), (-1, 'Dislike')], default=0),
        ),
    ]
