# Generated by Django 4.0.4 on 2022-05-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_like_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reputation',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
